name: dsmanager
channels:
  - conda-forge
  - defaults
dependencies:
  - notebook>=5.3
  - tornado>=6.1.0
  - jupyterlab=3
  - jupyter_bokeh=2.0.4
  - ipywidgets=7.6.3
  - ipysheet=0.4.4
  - jupyterlab-snippets=0.3.2
  - jupyter_bokeh=2.0.4
  - pandas=1.2.1
  - matplotlib=3.3.3
  - numpy=1.19.5
  - scipy=1.6.0
  - scikit-learn=0.24.1
  - sklearn-pandas=2.0.4
  - qgrid=1.3.1
  - seaborn=0.11.1
  - bokeh=2.2.3
  - nodejs
  - pip:
      - git+https://github.com/blaze/dask.git#egg=dask[complete]
      - business-duration==0.64
      - pandas-ui==0.1
      - classypandas==0.1
      - jupyterlab-widgets==1.0.0
      - ipywidgets-extended==1.0.5
      - pandas-bokeh==0.5.2
      - ipywidgets_bokeh==1.0.2
