#!/bin/bash

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager --minimize=False

# Import the workspace into JupyterLab
# jupyter lab workspaces import binder/workspace.json
jupyter lab workspaces import workspace.json
